version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: metrobus-api
    build: ./api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api/:/app/
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  db:
    container_name: metrobus_data
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5423:5432"
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
